### ISSUE TITLE
Bug: Users can type special chars into search

### ISSUE THREAD

**Issue by DefiledSpec** [gustbrad/mehyoutubeplayer#14]
## Bug
Users are able to input special chars into the search bar, specifically the '&' symbol, this will lead to bugs in the api calls to youtube.

## Possible Fixes
We could use a regex to strip out any special chars and replace them with ```''```

**Comment by gustbrad** [comment]
fixed by adding validation for pasting it will remove any sp characters we specify. For typing it will prevent the character upon keydown.

**Comment by DefiledSpec** [comment]
Users aren't able to type in a space into their search query.
Perhaps we can change spaces to '_'.
I'll have a look into the youtube api and see how it handles spaces in its requests.
