### ISSUE TITLE
Search Input Needed

### ISSUE THREAD

**Issue by DefiledSpec** [gustbrad/mehyoutubeplayer#6]
## User Story
As a user, I want to be able to input search queries so that I can search YouTube when I'm at work.

## Acceptance Criteria
- [x] Add a search input to the html for searching YouTube.
- [x] On search button click, return a list of results from YouTube.

**Comment by harshyadav9** [comment]
I would like to take this up.

**Comment by DefiledSpec** [comment]
I think if we put the search button into the ```<form>``` element for the search input and  give it a ```type="submit"```  we should be able to press enter to search.

**Comment by DefiledSpec** [comment]
@harshyadav9 Thanks for the offer, but this is a group project for school.

**Comment by harshyadav9** [comment]
ok no problem.:)
